cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - node_modules

test_async_node:
  image: node:latest
  script:
    - npm install
    - npm run depcruise
    - npm run lint
    - npm run test:cover
  except:
    - tags

pages:
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - tags
    - web
