name: install, lint, test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
env:
  NODE_LATEST: 18.x
  CI: true
defaults:
  run:
    shell: bash
jobs:
  check-linux:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: install
        run: |
          npm install
          apt-fast --assume-yes install graphviz
      - name: lint (on node ${{env.NODE_LATEST}} only)
        if: matrix.node-version == env.NODE_LATEST
        run: |
          npm run depcruise:github-actions:markdown
          npm run depcruise:github-actions:mermaid
          npm run depcruise
          npm run lint
      - name: test (on node != ${{env.NODE_LATEST}} only)
        if: matrix.node-version != env.NODE_LATEST
        run: npm test
      - name: test coverage (on node ${{env.NODE_LATEST}} only)
        if: matrix.node-version == env.NODE_LATEST
        run: npm run test:cover
      - name: report coverage to code climate (on node ${{env.NODE_LATEST}} only)
        if: matrix.node-version == env.NODE_LATEST
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_COVERAGE_ID }}

  check-macos:
    strategy:
      fail-fast: false
    env:
      PLATFORM: macos-latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_LATEST}}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{env.NODE_LATEST}}@${{env.PLATFORM}}-build-${{hashFiles('package.json')}}
          restore-keys: ${{env.NODE_LATEST}}@${{env.PLATFORM}}-build-
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: install
        run: |
          npm install
          brew install graphviz
      - name: test coverage
        run: npm run test:cover

  check-windows:
    strategy:
      fail-fast: false
    env:
      PLATFORM: windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_LATEST}}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: install
        run: npm install
      - name: test
        run: npm test
